const BLACK_CARDS = [
  // Custom Cards
  { text: "Taran ____ and ____.", pick: 2 },
  { text: "Isaac ____ and ____.", pick: 2 },
  { text: "Oliver ____ and ____.", pick: 2 },
  { text: "Henry ____ and ____.", pick: 2 },
  { text: "Zak ____ and ____.", pick: 2 },
  { text: "Michael ____ and ____.", pick: 2 },
  { text: "Taran likes ____", pick: 1 },
  { text: "Isaac likes ____", pick: 1 },
  { text: "Oliver likes ____", pick: 1 },
  { text: "Henry likes ____", pick: 1 },
  { text: "Zak likes ____", pick: 1 },
  { text: "Michael likes ____", pick: 1 },
  { text: "Georgina Harris is really ____ and loves to ____", pick: 2 },
  { text: "Sandra West is really ____ and loves to ____", pick: 2 },
  { text: "Malcolm West is really ____ and loves to ____", pick: 2 },
  { text: "Jacob Maynard is really ____ and loves to ____", pick: 2 },
  { text: "Francis Maynard is really ____ and loves to ____", pick: 2 },
  { text: "Victoria Vickery is really ____ and loves to ____", pick: 2 },
  { text: "Baby Vasudevan is really ____ and loves to ____", pick: 2 },
  { text: "Vandana Vasudevan is really ____ and loves to ____", pick: 2 },
  { text: "Ian Miller is really ____ and loves to ____", pick: 2 },
  { text: "Elaine Watson is really ____ and loves to ____", pick: 2 },
  
  // From Family Edition
  { text: "I don't really know what my mom's job is, but I think it has something to do with ____.", pick: 1 },
  { text: "Papa, come quickly! There, in the garden! Do you see ____? Tell me you see it, Papa!", pick: 1 },
  { text: "Attention students! Principal Butthead is at home recovering from ____. We hope he'll be back soon.", pick: 1 },
  { text: "I'm sorry, Jordan, but that's not an acceptable Science Fair project. That's just ____.", pick: 1 },
  { text: "The warm August air was filled with change. Things were different, for Kayla was now ____.", pick: 1 },
  { text: "This is gonna be the best sleepover ever. Once Mom goes to bed, it's time for ____!", pick: 1 },
  { text: "Coming soon! Batman vs. ____.", pick: 1 },
  { text: "Class, pay close attention. I will now demonstrate the physics of ____.", pick: 1 },
  { text: "Hey Riley, I'll give you five bucks if you try ____.", pick: 1 },
  { text: "When I look in the mirror, I see ____.", pick: 1 },
  { text: "My dad and I enjoy ____ together.", pick: 1 },
  { text: "Hey, kids. I'm Sensei Todd. Today, I'm gonna teach you how to defend yourself against ____.", pick: 1 },
  { text: "MY NAME CHUNGO. CHUNGO LOVE ____.", pick: 1 },
  { text: "Never fear, Captain ____ is here!", pick: 1 },
  { text: "Kids, Dad is trying something new this week. It's called '____.'", pick: 1 },
  { text: "Oh, no thank you, Mrs. Lee. I've had plenty of ____ for now.", pick: 1 },
  { text: "Time to put on my favorite t-shirt, the one that says 'I ____.'", pick: 1 },
  { text: "And over here is Picasso's most famous painting, 'Portrait of ____.'", pick: 1 },
  { text: "The aliens are here. They want ____.", pick: 1 },
  { text: "They call me 'Mr. ____.'", pick: 1 },
  { text: "CHUNGO FEEL SICK. CHUNGO NO LIKE ____ ANYMORE.", pick: 1 },
  { text: "Mom!? You have to come pick me up! There's ____ at this party!", pick: 1 },
  { text: "CNN breaking news! Over half of Americans are now ____.", pick: 1 },
  { text: "On the next episode of Dora the Explorer, Dora explores ____.", pick: 1 },
  { text: "Alright, which one of you little turds is responsible for ____?!", pick: 1 },
  { text: "Ladies and gentlemen, I have discovered something amazing. I have discovered ____.", pick: 1 },
  { text: "And in the blue corner, weighing in at 280 pounds, it's Tommy '____' Takahashi!", pick: 1 },
  { text: "Outback Steakhouse: No rules. Just ____.", pick: 1 },
  { text: "Ew. Grandpa smells like ____.", pick: 1 },
  { text: "My name is Peter Parker. I was bitten by a radioactive spider, and now I'm ____.", pick: 1 },
  { text: "Put on your helmet, strap on your goggles, and get ready for ____!", pick: 1 },
  { text: "Attention students! This is Principal Butthead reminding you that we do not allow ____ in the hallway. Thank you.", pick: 1 },
  { text: "What's about to take this school dance to the next level?", pick: 1 },
  { text: "Little Miss Muffet sat on a tuffet eating her curds and ____.", pick: 1 },
  { text: "All I want for Christmas is ____.", pick: 1 },
  { text: "Me and my friends don't play with dolls anymore. We're into ____ now.", pick: 1 },
  { text: "We're not supposed to go in the attic. My parents keep ____ in there.", pick: 1 },
  { text: "Police! Arrest this man! He's ____.", pick: 1 },
  { text: "My favorite dinosaur is '____asaurus.'", pick: 1 },
  { text: "When I pooped, what came out of my butt?", pick: 1 },
  { text: "I'm not like the other children. Toys bore me, and I don't care for sweets. I prefer ____.", pick: 1 },
  { text: "I'm sorry, Mrs. Sanchez, but I couldn't finish my homework because of ____.", pick: 1 },
  { text: "Oh Dark Lord, we show our devotion with a humble offering of ____!", pick: 1 },
  { text: "Thanks for watching! If you want to see more vids of ____, smash that subscribe.", pick: 1 },
  { text: "We're off to see the wizard, the wonderful wizard of ____!", pick: 1 },
  { text: "What's all fun and games until somebody gets hurt?", pick: 1 },
  { text: "Young lady, we do not allow ____ at the dinner table.", pick: 1 },
  { text: "Welcome! We're glad you're here. Now sit back, relax, and enjoy ____.", pick: 1 },
  { text: "My favorite book is The Amazing Adventures of ____.", pick: 1 },
  { text: "Well, look what we have here! A big fancy man walkin' in like he's ____.", pick: 1 },
  { text: "ENOUGH! I will not let ____ tear this family apart!", pick: 1 },
  { text: "Rub a dub dub, ____ in a tub!", pick: 1 },
  { text: "Madam President, we've run out of time. The only option is ____.", pick: 1 },
  { text: "I have invented a new sport. I call it '____ ball.'", pick: 1 },
  { text: "Hey, check out my band! We're called 'Rage Against ____.'", pick: 1 },
  { text: "Moms love ____.", pick: 1 },
  { text: "Where do babies come from?", pick: 1 },
  { text: "CHUNGO ANGRY. CHUNGO DESTROY ____.", pick: 1 },
  { text: "At school, I'm just Mandy. But at summer camp, I'm '____ Mandy.'", pick: 1 },
  { text: "Did you hear about the new Avenger? She's ____!", pick: 1 },
  { text: "It's BIG. It's SCARY. It's ____!", pick: 1 },
  { text: "Disney proudly presents: '____ on Ice.'", pick: 1 },
  { text: "What really killed the dinosaurs?", pick: 1 },
  { text: "Beep beep! ____ coming through!", pick: 1 },
  { text: "New from McDonald's: it's the Mc____ Burger.", pick: 1 },
  { text: "You don't love me, Sam. All you care about is ____.", pick: 1 },
  { text: "Did you know that Benjamin Franklin invented ____?", pick: 1 },
  { text: "'On the 12th day of Christmas, my true love gave to me: ____.'", pick: 1 },
  { text: "The easiest way to tell me and my twin apart is that I have a freckle on my cheek and she's ____.", pick: 1 },
  { text: "Hey guys. I just want to tell all my followers who are struggling with ____: it DOES get better.", pick: 1 },
  { text: "You're grounded, young lady! No ____ for a whole week.", pick: 1 },
  { text: "Princess Marigold, the kingdom is in danger! You must stop ____.", pick: 1 },
  { text: "Shut up, Becky! At least I'm not ____.", pick: 1 },
  { text: "I lost my arm in a ____ accident.", pick: 1 },
  { text: "Isn't this great, honey? Just you, me, the kids, and ____.", pick: 1 },
  { text: "Foolish child! Did you think you could escape from ____?", pick: 1 },
  { text: "Girls just wanna have ____.", pick: 1 },
  { text: "Run, run, as fast as you can. You can't catch me, I'm ____!", pick: 1 },
  { text: "New from Mattel, it's ____ Barbie!", pick: 1 },
  { text: "No fair! How come Chloe gets her own phone, and all I get is ____?", pick: 1 },
  { text: "Bow before me, for I am the Queen of ____!", pick: 1 },
  { text: "New from Hasbro! It's BUNGO: The Game of ____.", pick: 1 },
  { text: "Our day at the water park was totally ruined by ____.", pick: 1 },
  { text: "Alright, kids. The votes are in, and the new school mascot will be ____!", pick: 1 },
  { text: "What killed Old Jim?", pick: 1 },
  { text: "Next from J.K. Rowling: Harry Potter and the Chamber of ____.", pick: 1 },
  { text: "What's keeping Dad so busy in the garage?", pick: 1 },
  { text: "Boys? No. ____? Yes!", pick: 1 },
  { text: "ME HUNGRY. ME WANT ____.", pick: 1 },
  { text: "Oh, that's my mom's friend Carl. He comes over and helps her with ____.", pick: 1 },
  { text: "Guys, stop it! There's nothing funny about ____.", pick: 1 },
  { text: "Huddle up, Wildcats! They may be bigger. They may be faster. But we've got a secret weapon: ____.", pick: 1 },
  { text: "Coming to theaters this holiday season, 'Star Wars: The Rise of ____.'", pick: 1 },
  { text: "I do not fight for wealth. I do not fight for glory. I fight for ____!", pick: 1 },
  { text: "Come on, Danny. All the cool kids are doin' it. Wanna try ____?", pick: 1 },

  // From Main Game (US)
  { text: "Hey Reddit! I'm ____. Ask me anything.", pick: 1 },
  { text: "Introducing X-treme Baseball! It's like baseball, but with ____!", pick: 1 },
  { text: "What is Batman's guilty pleasure?", pick: 1 },
  { text: "TSA guidelines now prohibit ____ on airplanes.", pick: 1 },
  { text: "That's right, I killed ____. How, you ask? ____.", pick: 2 },
  { text: "I'm sorry, Professor, but I couldn't complete my homework because of ____.", pick: 1 },
  { text: "And the Academy Award for ____ goes to ____.", pick: 2 },
  { text: "Dude, do not go in that bathroom. There's ____ in there.", pick: 1 },
  { text: "How did I lose my virginity?", pick: 1 },
  { text: "It's a pity that kids these days are all getting involved with ____.", pick: 1 },
  { text: "Step 1: ____. Step 2: ____. Step 3: Profit.", pick: 2 },
  { text: "____. Betcha can't have just one!", pick: 1 },
  { text: "Kids, I don't need drugs to get high. I'm high on ____.", pick: 1 },
  { text: "For my next trick, I will pull ____ out of ____.", pick: 2 },
  { text: "Mitch McConnell can't cum without ____.", pick: 1 },
  { text: "In the new Disney Channel Original Movie, Hannah Montana struggles with ____ for the first time.", pick: 1 },
  { text: "What's my secret power?", pick: 1 },
  { text: "I'm going on a cleanse this week. Nothing but kale juice and ____.", pick: 1 },
  { text: "____ + ____ = ____.", pick: 3 },
  { text: "When Pharaoh remained unmoved, Moses called down a Plague of ____.", pick: 1 },
  { text: "Just once, I'd like to hear you say 'Thanks, Mom. Thanks for ____.'", pick: 1 },
  { text: "Daddy, why is mommy crying?", pick: 1 },
  { text: "When I was tripping on acid, ____ turned into ____.", pick: 2 },
  { text: "50% of all marriages end in ____.", pick: 1 },
  { text: "My fellow Americans: Before this decade is out, we will have ____ on the moon!", pick: 1 },
  { text: "This season at Steppenwolf, Samuel Beckett's classic existential play: Waiting for ____.", pick: 1 },
  { text: "Instead of coal, Santa now gives the bad children ____.", pick: 1 },
  { text: "Life for American Indians was forever changed when the White Man introduced them to ____.", pick: 1 },
  { text: "What's Teach For America using to inspire inner city students to succeed?", pick: 1 },
  { text: "Maybe she's born with it. Maybe it's ____.", pick: 1 },
  { text: "My name is Peter Parker. I was bitten by a radioactive spider, and now I'm ____.", pick: 1 },
  { text: "White people like ____.", pick: 1 },
  { text: "____ is a slippery slope that leads to ____.", pick: 2 },
  { text: "Why do I hurt all over?", pick: 1 },
  { text: "A romantic, candlelit dinner would be incomplete without ____.", pick: 1 },
  { text: "Just saw this upsetting video! Please retweet!! #stop____", pick: 1 },
  { text: "Fun tip! When your man asks you to go down on him, try surprising him with ____ instead.", pick: 1 },
  { text: "The class field trip was completely ruined by ____.", pick: 1 },
  { text: "What's a girl's best friend?", pick: 1 },
  { text: "Dear Abby, I'm having some trouble with ____ and would like your advice.", pick: 1 },
  { text: "In Jordan Peele's new thriller, a young family discovers that ____ had really been ____ all along.", pick: 2 },
  { text: "When I am President, I will create the Department of ____.", pick: 1 },
  { text: "What are my parents hiding from me?", pick: 1 },
  { text: "What never fails to liven up the party?", pick: 1 },
  { text: "IF you like ____, YOU MIGHT BE A REDNECK.", pick: 1 },
  { text: "Make a haiku.", pick: 3 },
  { text: "What made my first kiss so awkward?", pick: 1 },
  { text: "Hey guys, welcome to Chili's! Would you like to start the night off right with ____?", pick: 1 },
  { text: "I got 99 problems but ____ ain't one.", pick: 1 },
  { text: "____. It's a trap!", pick: 1 },
  { text: "Hulu's new reality show features twelve hot singles living with ____.", pick: 1 },
  { text: "What would grandma find disturbing, yet oddly charming?", pick: 1 },
  { text: "____. That was so metal.", pick: 1 },
  { text: "I never truly understood ____ until I encountered ____.", pick: 2 },
  { text: "During sex, I like to think about ____.", pick: 1 },
  { text: "What ended my last relationship?", pick: 1 },
  { text: "What's that sound?", pick: 1 },
  { text: "Uh, hey guys, I know this was my idea, but I'm having serious doubts about ____.", pick: 1 },
  { text: "Why am I sticky?", pick: 1 },
  { text: "I'm no doctor, but I'm pretty sure what you're suffering from is called '____.'", pick: 1 },
  { text: "What's there a ton of in heaven?", pick: 1 },
  { text: "After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: ____.", pick: 1 },
  { text: "What will always get you laid?", pick: 1 },
  { text: "They said we were crazy. They said we couldn't put ____ inside of ____. They were wrong.", pick: 2 },
  { text: "Lifetime® presents '____: the Story of ____.'", pick: 2 },
  { text: "____: kid-tested, mother-approved.", pick: 1 },
  { text: "Why can't I sleep at night?", pick: 1 },
  { text: "What's that smell?", pick: 1 },
  { text: "Why is Brett so sweaty?", pick: 1 },
  { text: "This is the way the world ends. This is the way the world ends. Not with a bang but with ____.", pick: 1 },
  { text: "Coming to Broadway this season, ____: The Musical.", pick: 1 },
  { text: "Here is the church. Here is the steeple. Open the doors. And there is ____.", pick: 1 },
  { text: "But before I kill you, Mr. Bond, I must show you ____.", pick: 1 },
  { text: "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ____.", pick: 1 },
  { text: "Introducing the amazing superhero/sidekick duo! It's ____ and ____!", pick: 2 },
  { text: "Next on ESPN2: The World Series of ____.", pick: 1 },
  { text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate ____.", pick: 1 },
  { text: "Military historians remember Alexander the Great for his brilliant use of ____ against the Persians.", pick: 1 },
  { text: "War! What is it good for?", pick: 1 },
  { text: "What gives me uncontrollable gas?", pick: 1 },
  { text: "The new Chevy Tahoe. With the power and space to take ____ everywhere you go.", pick: 1 },
  { text: "Well if you'll excuse me, gentlemen, I have a date with ____.", pick: 1 },
  { text: "Alternative medicine is now embracing the curative powers of ____.", pick: 1 },
  { text: "As the mom of five rambunctious boys, I'm no stranger to ____.", pick: 1 },
  { text: "____. High five, bro.", pick: 1 },
  { text: "Today on Maury: 'Help! My son is ____!'", pick: 1 },
  { text: "I get by with a little help from ____.", pick: 1 },
  { text: "★☆☆☆☆ Do NOT go here! Found ____ in my fettuccine alfredo!", pick: 1 },
  { text: "I drink to forget ____.", pick: 1 },
  { text: "I'm LeBron James, and when I'm not slamming dunks, I love ____.", pick: 1 },
  { text: "What makes life worth living?", pick: 1 },
  { text: "Arby's: We Have ____.", pick: 1 },
  { text: "Mr. and Mrs. Diaz, we called you in because we're concerned about Cynthia. Are you aware that your daughter is ____?", pick: 1 },
  { text: "If you can't be with the one you love, love ____.", pick: 1 },
  { text: "Brought to you by Bud Light®, the Official Beer of ____.", pick: 1 },
  { text: "Click Here for ____!!!", pick: 1 },
  { text: "Check me out, yo! I call this dance move '____.'", pick: 1 },
  { text: "Old MacDonald had ____. E-I-E-I-O.", pick: 1 },
  { text: "Men's Wearhouse: You're gonna like ____. I guarantee it.", pick: 1 },

  // From UK Edition
  { text: "TFL apologizes for the delay in train service due to ____.", pick: 1 },
  { text: "★☆☆☆☆ Do NOT go here! Found ____ in my spaghetti bolognese!", pick: 1 },
  { text: "Nobody expects the Spanish Inquisition. Our chief weapons are fear, surprise, and ____.", pick: 1 },
  { text: "In a world ravaged by ____, our only solace is ____.", pick: 2 },
  { text: "Coming to the West End this year, ____: The Musical.", pick: 1 },
  { text: "When Pharaoh remained unmoved, Moses called down a Plague of ____.", pick: 1 },
  { text: "What are my parents hiding from me?", pick: 1 },
  { text: "What's a girl's best friend?", pick: 1 },
  { text: "Fun tip! When your man asks you to go down on him, try surprising him with ____ instead.", pick: 1 },
  { text: "What is Batman's guilty pleasure?", pick: 1 },
  { text: "____ + ____ = ____.", pick: 3 },
  { text: "That's right, I killed ____. How, you ask? ____.", pick: 2 },
  { text: "What's my secret power?", pick: 1 },
  { text: "Daddy, why is mummy crying?", pick: 1 },
  { text: "They said we were crazy. They said we couldn't put ____ inside of ____. They were wrong.", pick: 2 },
  { text: "Introducing the amazing superhero/sidekick duo! It's ____ and ____!", pick: 2 },
  { text: "Just once, I'd like to hear you say 'Thanks, Mum. Thanks for ____.'", pick: 1 },
  { text: "When I was tripping on acid, ____ turned into ____.", pick: 2 },
  { text: "50% of all marriages end in ____.", pick: 1 },
  { text: "My fellow Americans: Before this decade is out, we will have ____ on the moon!", pick: 1 },
  { text: "This season at the Old Vic, Samuel Beckett's classic existential play, Waiting for ____.", pick: 1 },
  { text: "Instead of coal, Father Christmas now gives bad children ____.", pick: 1 },
  { text: "Life for American Indians was forever changed when the White Man introduced them to ____.", pick: 1 },
  { text: "White people like ____.", pick: 1 },
  { text: "____ is a slippery slope that leads to ____.", pick: 2 },
  { text: "Why do I hurt all over?", pick: 1 },
  { text: "A romantic, candlelit dinner would be incomplete without ____.", pick: 1 },
  { text: "Just saw this upsetting video! Please retweet!! #stop____", pick: 1 },
  { text: "The school trip was completely ruined by ____.", pick: 1 },
  { text: "Dear Agony Aunt, I'm having some trouble with ____ and I need your advice.", pick: 1 },
  { text: "Maybe she's born with it. Maybe it's ____.", pick: 1 },
  { text: "Next up on Channel 4: Ramsay's ____ Nightmares.", pick: 1 },
  { text: "When I am Prime Minister of the United Kingdom, I will create the Ministry of ____.", pick: 1 },
  { text: "Why is Alan so sweaty?", pick: 1 },
  { text: "UKIP: Putting ____ First!", pick: 1 },
  { text: "What will always get you laid?", pick: 1 },
  { text: "How did I lose my virginity?", pick: 1 },
  { text: "Next from J.K. Rowling: Harry Potter and the Chamber of ____.", pick: 1 },
  { text: "What made my first kiss so awkward?", pick: 1 },
  { text: "Uh, hey guys, I know this was my idea, but I'm having serious doubts about ____.", pick: 1 },
  { text: "In a world ravaged by ____, our only solace is ____.", pick: 2 },
  { text: "I get by with a little help from ____.", pick: 1 },
  { text: "____? Jim'll fix it!", pick: 1 },
  { text: "Hey Reddit! I'm ____. Ask me anything.", pick: 1 },
  { text: "What are my parents hiding from me?", pick: 1 },
  { text: "What would grandma find disturbing, yet oddly charming?", pick: 1 },
  { text: "What's that sound?", pick: 1 },
  { text: "How am I maintaining my relationship status?", pick: 1 },
  { text: "I'm no doctor, but I'm pretty sure what you're suffering from is called '____.'", pick: 1 },
  { text: "What never fails to liven up the party?", pick: 1 },
  { text: "War! What is it good for?", pick: 1 },
  { text: "This is the way the world ends. This is the way the world ends. Not with a bang but with ____.", pick: 1 },
  { text: "The school trip was completely ruined by ____.", pick: 1 },
  { text: "Instead of coal, Father Christmas now gives bad children ____.", pick: 1 },
  { text: "Why can't I sleep at night?", pick: 1 },
  { text: "Well if you'll excuse me, gentlemen, I have a date with ____.", pick: 1 },
  { text: "Netflix's new reality show features twelve hot singles living with ____.", pick: 1 },
  { text: "What gives me uncontrollable gas?", pick: 1 },
  { text: "I'm sorry, Sir, but I couldn't complete my homework because of ____.", pick: 1 },
  { text: "Now at the Natural History Museum: an interactive exhibit on ____.", pick: 1 },
  { text: "Channel 4 presents ____, the story of ____.", pick: 2 },
  { text: "I never truly understood ____ until I encountered ____.", pick: 2 },
  { text: "What would grandma find disturbing, yet oddly charming?", pick: 1 },
  { text: "What's that sound?", pick: 1 },
  { text: "Today on The Jeremy Kyle Show: 'Help! My son is ____!'", pick: 1 },
  { text: "During sex, I like to think about ____.", pick: 1 },
  { text: "What's that smell?", pick: 1 },
  { text: "____. That was so metal.", pick: 1 },
  { text: "And the BAFTA for ____ goes to ____.", pick: 2 },
  { text: "For my next trick, I will pull ____ out of ____.", pick: 2 },
  { text: "Mr. and Mrs. Diaz, we called you in because we're concerned about Cynthia. Are you aware that your daughter is ____?", pick: 1 },
  { text: "Next on Sky Sports: The World Championship of ____.", pick: 1 },
  { text: "But before I kill you, Mr. Bond, I must show you ____.", pick: 1 },
  { text: "Check me out, yo! I call this dance move '____.'", pick: 1 },
  { text: "Old MacDonald had ____. E-I-E-I-O.", pick: 1 },
  { text: "Make a haiku.", pick: 3 },
  { text: "What's that smell?", pick: 1 },
  { text: "Kids, I don't need drugs to get high. I'm on high on ____.", pick: 1 },
  { text: "What did I bring back from Amsterdam?", pick: 1 },
  { text: "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ____.", pick: 1 },
  { text: "After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: ____.", pick: 1 },
  { text: "Mate, do not go in that bathroom. There's ____ in there.", pick: 1 },
  { text: "50% of all marriages end in ____.", pick: 1 },
  { text: "I'm going on a cleanse this week. Nothing but kale juice and ____.", pick: 1 },
  { text: "Click Here For ____!!!", pick: 1 },
  { text: "It's a pity that kids these days are all getting involved with ____.", pick: 1 },
  { text: "Military historians remember Alexander the Great for his brilliant use of ____ against the Persians.", pick: 1 },
  { text: "What are my parents hiding from me?", pick: 1 },
  { text: "When I am Prime Minister of the United Kingdom, I will create the Ministry of ____.", pick: 1 },
  { text: "Alternative medicine is now embracing the curative powers of ____.", pick: 1 },
  { text: "What makes life worth living?", pick: 1 },
  { text: "What's the next Happy Meal® toy?", pick: 1 },
  { text: "Hey guys, welcome to TGI Fridays! Would you like to start the night off right with ____?", pick: 1 },
  { text: "What's George W. Bush thinking about right now?", pick: 1 },
  { text: "____: kid-tested, mother-approved.", pick: 1 },
  { text: "____. It's a trap!", pick: 1 },
  { text: "If you can't be with the one you love, love ____.", pick: 1 },
  { text: "The theme for next year's Eurovision Song Contest is 'We are ____.'", pick: 1 },
  { text: "A romantic, candlelit dinner would be incomplete without ____.", pick: 1 },
  { text: "I got 99 problems but ____ ain't one.", pick: 1 },
  { text: "Why am I sticky?", pick: 1 },
  { text: "In Belmarsh Prison, word is you can trade 200 cigarettes for ____.", pick: 1 },
  { text: "Step 1: ____. Step 2: ____. Step 3: Profit.", pick: 2 },
  { text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate ____.", pick: 1 },
  { text: "What's there a ton of in heaven?", pick: 1 },
];

const WHITE_CARDS = [
  // Custom Cards
  "= Bowling ball",
  "= Curry muncher",
  "Reeks of shit",
  "Is a femboy",
  "Goons to Minecraft Steve",
  "Is built like a cube",
  "Is built like a 1 by 1 lego brick",
  "Goons to Hornet",
  "Goons to The Knight",
  "Has fungly cheesy feet",
  "LOVES Minurazi",
  "Likes Freya Small",
  "Likes Isla (again)",
  "Is an ABSOLUTE CURRY MUNCHER",
  "Everyone is gooning",
  "Everyone is oiled up",
  "Has Ian Miller showing off his feet",
  "Whoever loses gets 50,000 volts to the nipples",
  
  // Family Edition
  "A big wet kiss from Great Aunt Sharon",
  "A cloud that rains diarrhea",
  "A caveperson named Helen",
  "Acting kinda sus",
  "All of your teeth falling out",
  "Beautiful Grandma",
  "Defecating on the neighbor's lawn",
  "Eight hours of video games",
  "Going night-night",
  "Hanging out with Zendaya",
  "Kissing Mom on the lips",
  "Me, your dad",
  "Playing trumpet for the Mayor",
  "Ratzilla",
  "Teeny tiny turds",
  "That there tarantula",
  "The way Grandpa smells",
  "Three glasses of red wine",
  "Whatever Dad does at work",
  "Getting shot out of a cannon",
  "Jesus",
  "Eating pasta out of my pants",
  "A burrito smoothie",
  "A bear",
  "Old people",
  "My sister's stupid boyfriend",
  "Stuffing my underwear with pancakes",
  "Stinky Martha, the superhero that nobody likes",
  "My chainsaw",
  "Diarrhea",
  "Boogers",
  "The police",
  "Sniffing a dog's butt",
  "Horrible allergies",
  "Your face",
  "A gerbil named 'Gerbil'",
  "Fartus Magnimus, God of Beans",
  "Rated-R stuff",
  "Blowing up the Moon",
  "Getting launched into space",
  "Likes",
  "A bird pooping on the president's head",
  "Chungo, the talking gorilla",
  "The way I feel when I see Kyle",
  "Hot gossip",
  "Forgetting to put on underwear",
  "Running full speed into a wall",
  "The Russians",
  "A black hole",
  "Putting my butt on stuff",
  "Racism, sexism, and homophobia",
  "Making the bees angry",
  "My strong, terrifying daughter",
  "A Democrat",
  "TikTok",
  "Cheeto fingers",
  "A huge honkin' carrot",
  "The country of Bolivia",
  "My parents",
  "Idiots",
  "Filling my butt with spaghetti",
  "Putting an apple in a little boy's mouth and roasting him for dinner",
  "Taking a dump in the backyard and blaming it on the dog",
  "Climbing into a cow's butt",
  "Work",
  "Mashing a banana into your belly button",
  "China",
  "Shrek",
  "Cavities",
  "Eating people",
  "Butts of all shapes and sizes",
  "A 40-piece Chicken McNuggets",
  "Climate change",
  "Barf",
  "A poop as big as Mom",
  "A couch that eats children",
  "Going to Hell",
  "The loose skin at the joint of the elbow known as 'the weenus'",
  "A horse with no legs",
  "Fat stacks of cash",
  "Dora the Explorer",
  "Illegal drugs",
  "Cold, wet garlic bread",
  "Dad's meatloaf",
  "Extra-warm Pepsi",
  "The old man with the rake who lives down the dark and winding road",
  "Calling 9-1-1",
  "Spending my parents' hard-earned money",
  "Toe jam",
  "Hot lava",
  "Butt surgery",
  "Freeing all the animals from the zoo",
  "A bountiful harvest of squashes and corns",
  "Bombs",
  "Boobies",
  "Respecting personal boundaries",
  "Having no idea what's going on",
  "John Wilkes Booth",
  "Getting married",
  "Politics",
  "Garbage",
  "Naked people",
  "This stupid game",
  "Biting a rich person",
  "Screaming at birds",
  "Getting stuck in the toilet",
  "Getting crushed by a piano",
  "Huge pants",
  "Mom's spaghetti",
  "An old, dirty cat with bad breath",
  "A corn dog",
  "Hot wet garbage",
  "Principal Butthead",
  "A statue of a naked guy",
  "A chicken that has pickles as horns and a butt the size of a bus",
  "Joining the army",
  "Witchcraft",
  "Taking out my eyeballs",
  "Sacrificing Uncle Tim",
  "Moving to Ohio",
  "A hundred screaming monkeys",
  "A dinosaur that is pooping but doesn't know it is pooping",
  "Emotions",
  "Ham",
  "Clams",
  "Spider-Man",
  "Drinking out of the toilet and eating garbage",
  "Trying to catch that dang raccoon",
  "Slapping my huge belly",
  "The doll that watches me sleep",
  "Money",
  "LeBron James",
  "Divorce",
  "Me",
  "Salmon",
  "Screaming the F-word",
  "A whole thing of cottage cheese",
  "Crab-walking from the toilet to get more toilet paper",
  "Mayonnaise",
  "Total world domination",
  "Failure",
  "JoJo Siwa",
  "Getting kicked in the nuts",
  "Farting and walking away",
  "Sharks with legs",
  "Triangles",
  "Ninjas",
  "The floor",
  "The whole family",
  "Bench pressing a horse",
  "Spiders",
  "Uranus",
  "A Republican",
  "Giving wedgies to my haters",
  "'Baby Shark' on repeat forever",
  "Big Randy",
  "Blasting my math teacher into the sun",
  "Dreaming about boys",
  "Taking a dump in the pool",
  "Crying in the bathroom",
  "Happiness",
  "Poison",
  "Hot, juicy broccoli farts",
  "A scoop of tuna",
  "Doing karate",
  "Eating bicycles to somehow become famous",
  "Lil Nas X",
  "Dad's famous poops",
  "Squirty cheese",
  "My girlfriend, who goes to another school",
  "Having too many fingers",
  "Slapping that butt",
  "Questioning authority",
  "Chugging a gallon of milk and then vomiting a gallon of milk",
  "Farting a lot today",
  "Going bald",
  "Germs",
  "Nuclear war",
  "Barfing into a popcorn bucket",
  "A cursed llama with no eyes",
  "The wettest fart you ever heard",
  "Shaving Dad's back",
  "Overthrowing the government",
  "Murdering",
  "Exploding",
  "Bleeding",
  "The oppressive system of capitalism",
  "Saying 'I love you'",
  "A long, hot pee",
  "Throwing up double peace signs with your besties at Starbucks",
  "A balloon filled with chili",
  "Stealing dead bodies from the morgue",
  "The freedom of speech",
  "Egg salad",
  "Mom's friend, Donna",
  "Rich people",
  "Pirate music",
  "Being a dinosaur",
  "A fake kid made out of wood",
  "Homework",
  "Batman",
  "A dead body",
  "Drinking a whole bottle of ranch",
  "Destroying the planet",
  "Living in a pineapple under the sea",
  "Lovingly placing two bagel bites over the eyes of my dead brother",
  "This pumpkin",
  "Extremely tight underpants",
  "A nice, warm glass of pee",
  "Magical corn that makes you fart rainbows",
  "Complaining",
  "Bursting into flames",
  "Poop from the sky",
  "My whole body getting big and strong and beautiful",
  "Big, juicy pimples",
  "The humble earthworm",
  "The garbage man",
  "A big, and I mean BIG turtle",
  "Your mom!",
  "The octopus stuck to my face",
  "Dying of old age",
  "Pantaloons",
  "Screaming into a can of Pringles",
  "Grandpa",
  "Shutting up",
  "Silence",
  "My annoying brother",
  "My future husband",
  "A hot air balloon powered by fart gas",
  "Sitting on the toilet and going poop",
  "A screaming soccer dad",
  "Cocktail weenies",
  "The British",
  "WAR!",
  "Science",
  "Picking my nose and eating it",
  "Having a really big head",
  "A dead whale",
  "Eating a burger while farting on a manatee",
  "The power of the Dark Side",
  "Big butt cheeks filled with poop",
  "My friend Steve",
  "Violence",
  "Going live on Zoom without pants on",
  "Eating toenail clippings",
  "Using balloons as boobies",
  "My dang kids",
  "Squeezing a lemon into my eye",
  "Tombus, the talking rhombus",
  "Eating a rock, getting the rock stuck in your stomach, swallowing a second rock to push out the first rock, then getting that rock stuck, and then having to go to the emergency room",
  "Ellen",
  "Uncle Bob",
  "Outback Steakhouse",
  "Dwayne 'The Rock' Johnson",
  "A baby with a full mustache",
  "Getting hit in the face with a soccer ball",
  "Eating a whole roll of toilet paper",
  "The bacon",
  "The first female president of the United States",
  "Falling off a mountain",
  "Person milk",
  "Pink eye",
  "Pork",
  "The government",
  "JOHN CENAAAA!",
  "Nothing",
  "GOOOAAALLLL!!!",
  "Mom's new haircut",
  "Happy daddies with happy sandals",
  "Giggling and farting and slurping milkshakes",
  "Ice pee",
  "Obama",
  "Twerking",
  "Reading my sister's diary",
  "The ice cream man",
  "Love",
  "Raisins",
  "Living in the dumpster",
  "Having a baby",
  "Shoplifting",
  "My father, who is a walrus",
  "The dentist",
  "Aunt Linda",
  "One tough mama",
  "Releasing the falcons!",
  "Literally ruining my life",
  "Flushing myself down the toilet",
  "Fire farts",
  "Lice",
  "A big, fat, wiggly, squishy, talking, screaming turd",
  "Anti-vaxxers",
  "Wiping my butt",
  "Saying mean stuff and making people feel bad",
  "Beyoncé",
  "A truck",
  "Only beans",
  "The beautiful potato",
  "Legs",
  "The woman I'm going to marry one day",
  "Unleashing a hell demon that will destroy our world",
  "Feminism",
  "Lighting stuff on fire",
  "Turning 40",
  "Getting a skull tattoo",
  "An invisible giant who takes giant, visible poops",
  "A cowboy who is half boy, half cow",
  "The longest tongue in the world",
  "Josh",
  "Locking Mother in the pantry",
  "Ariana Grande",
  "Puberty",
  "A glorious beard",
  "A dog that stares into eternal nothingness",
  "Dumbness",
  "Farting, barfing, and passing out",
  "Flamin' Hot Cheetos",
  "Peeing in a glorious golden arc",
  "Eating a ham and cheese sandwich on March 24, 2022",
  "Niagara Falls, but with diarrhea instead of water",
  "My ex-wife",
  "Using my butt as a microwave",
  "Glen's fabulous body",
  "Gluten",
  "Who cares",
  "Many wolves",
  "One long hair growing out of a mole",
  "A butt that eats underwear",
  "Poo-poo",
  "Mooing",
  "Meat blindness",
  "Punching everyone",
  "How much wood a woodchuck would chuck if a woodchuck could chuck wood",
  "Swords",
  "Kevin's mom",
  "Getting scalded in the face with hot beans",
  "Chest hair",
  "My annoying sister",
  "Getting slapped with a fish",
  "Harry Potter",
  "Peeing sand",
  "Being French, hoh-hoh-hoh!",
  "Guacamole",
  "Getting naked",
  "A super angry cat I found outside",
  "Slappy Spatchy, the game where you slap each other with spatulas",
  "A pregnant person",
  "A bunch of dead squirrels on a trampoline",
  "Grandma panties",
  "Thick, nasty burps",
  "Having no bones",
  "Famous peanut scientist George Washington Carver",
  "Saving up my boogers for ten years and then building the world's largest booger",
  "Swallowing a bunch of popcorn kernels and shooting them out of my butt like a machine gun",
  "A hug",
  "The Dark Lord",
  "Being super serious right now",
  "Freeing a fart from its butt prison",
  "An order of mozzarella sticks",
  "Fake news",
  "The baby",
  "Like a million alligators",
  "Big, slappy hands",
  "Beer",
  "Spit",
  "The fifth graders",
  "Licking a goat",
  "A flamethrower",
  "Drama!",
  "Old Jim's Steamy Butt Sauce",
  "Going to the emergency room",
  "Sitting atop a pile of tuna, like some kind of tuna queen",
  "Girls",
  "A Pringle",
  "Never showering",
  "Hunky men",
  "The gym teacher",
  "Coming back from the dead",
  "Burning books",
  "Deep-frying Dad's laptop",
  "Violating the dress code",
  "Building a ladder of hot dogs to the moon",
  "Practicing kissing",
  "Eating a lightning bug to gain its lightning powers",
  "Slowly turning into cheese",
  "Whispering secrets to my best friend, Turkey",
  "Ear wax",
  "Knives",
  "Stuff",
  "Taking a selfie",
  "Dancing with my son",
  "Punching a guy through a wall",
  "Nipples",
  "Cat pee",
  "Cringe",
  "Billie Eilish",
  "Really bad Dad jokes",
  "Elegant party hats",
  "Santa Claus",
  "The gluteus maximus",
  "Baby Yoda",
  "Peeing in the cat's litter box",
  "A big sad dragon with no friends",
  "A big whiny cry-baby",
  "Seymour Butts",
  "The bus driver",
  "Getting run over by a train",
  "Spinning and barfing",
  "Some freakin' privacy",
  "Butt hair",
  "Having many husbands",
  "Making the bathroom smell",
  "Coffee",
  "Anime",
  "The sweet honking of Karen's bassoon",
  "Pooping in a bag and lighting it on fire",
  "Space lasers",
  "Being dead",
  "Pooping barf forever",
  "FOOOOD FIIIIIIIIIIIIIIIIIGHT!!!",
  "Wearing high heels",
  "A long, long snake",
  "Getting trampled by horses",
  "The babysitter",
  "The lunch lady",
  "Peeing on my poopy",
  "Not wearing pants",
  "Meatballs, meatballs, meatballs!",
  "Finding Waldo",
  "Going around sniffing people's armpits",
  "Stealing Mom's credit card",
  "Diaper beans",
  "Cigarettes",
  "Getting my ponytail stuck in my butt",
  "Looking into people's windows",
  "Sucking at life",
  "Covering my body with vaseline and sliding on the floor like a slug",
  "Evil",
  "A big rock",
  "Rubbing lotion on a hairless cat",
  "Goblins",
  "Nasty Cousin Amber",
  "Tongue kissing",
  "Abraham Lincoln",
  "Covering myself with ketchup and mustard because I am hot dog",
  "Hot, fresh doodies",
  "Feet",
  "Sadness",
  "Going beast mode",
  "An owl that hates you",
  "A doll that pees real pee!",
  "A naked lady in a painting",
  "Chunks",
  "Some weird guy",
  "Getting a girlfriend",
  "Falling in love with a hot dog",
  "Throwing stuff at other stuff",
  "Hogs",
  "A turd that just won't flush",
  "The entire state of Texas",
  "Showing everyone my butt",
  "My big donkey brother",
  "The huge, stupid moon",
  "Math",
  "Pee-pee",
  "Dinner",
  "Butthole",
  "Smelling like onions",
  "Being fake",
  "Peer pressure",
  "Peeing in my backpack",
  "Bad parenting",
  "Mom's butt",
  "One weird lookin' toe",
  "You",
  "Boys",
  "Sitting on a cake",
  "Teaching a chicken to kill",
  "The middle finger",
  "A bra",
  "Being famous on YouTube",
  "Cream",
  "Balls",
  "Having no friends",
  "Peeing into everyone's mouth",
  "Gluing my butt cheeks together",
  "How school slowly breaks your spirit and drains your will to live",
  "A Pokémon named 'Jim'",
  "True love's kiss",
  "Total crap",
  "Cool sunglasses",
  "Literally dying from the smell of a fart",
  "Snot bubbles",
  "Doing crimes and going to jail",
  "This goat, who is my friend",
  "Aliens",
  "School",
  "A cow",
  "The terrible winter of 1609",
  "Getting sucked into a jet engine",
  "Not breathing",
  "Licking a used band-aid",
  "Braiding my armpit hair",
  "Waking up inside of a spider web",
  "An eggy smell",
  "Getting hit by an airplane",

  // Main Game (US) white cards
  "Silence",
  "The illusion of choice in a late-stage capitalist society",
  "Many bats",
  "Hot Asian men",
  "Shame",
  "Website",
  "Assaulting a police officer",
  "Magnets",
  "A sorry excuse for a father",
  "Seeing what happens when you lock people in a room with hungry seagulls",
  "A crucifixion",
  "A narc",
  "Boneless buffalo wings",
  "A live studio audience",
  "Authentic Mexican cuisine",
  "Doing crimes",
  "COVID-19",
  "Crippling debt",
  "Daddy issues",
  "Working in an Amazon warehouse",
  "A fart so powerful that it wakes the giants from their thousand-year slumber",
  "Former President George W. Bush",
  "Full frontal nudity",
  "Covering myself with Parmesan cheese and chili flakes because I am pizza",
  "Laying an egg",
  "Getting naked and watching Nickelodeon",
  "Pretending to care",
  "Having big dreams but no realistic way to achieve them",
  "Seeing Grandma naked",
  "Boogers",
  "The Confederate flag",
  "The miracle of childbirth",
  "A positive attitude!",
  "Having a stroke",
  "White privilege",
  "Emerging from the sea and rampaging through Tokyo",
  "The Hamburglar",
  "The tampon from my vagina",
  "The Blood of Christ",
  "Soft, kissy missionary sex",
  "BATMAN!",
  "Agriculture",
  "Barely making $25,000 a year",
  "Natural selection",
  "Boomers",
  "Dropping a hot doodie out of my turd hole",
  "My abusive boyfriend who really isn't so bad once you get to know him",
  "Prescription pain killers",
  "Swooping",
  "Mansplaining",
  "A homoerotic volleyball montage",
  "Alexandria Ocasio-Cortez",
  "Putting things where they go",
  "Holding a pepper grinder for some reason",
  "Giving birth in prison",
  "An old guy who's almost dead",
  "Kanye West",
  "Hot cheese",
  "Getting serial killed",
  "Seven dead and three in critical condition",
  "Smegma",
  "Alcoholism",
  "A middle-aged man on roller skates",
  "Nobody giving a shit about anything anymore",
  "Grabbing my man by his love handles and fucking his big ass",
  "Stuffing my peehole with Tic Tacs",
  "Self-loathing",
  "Sitting on my face and telling me I'm garbage",
  "Half-assed foreplay",
  "The Holy Bible",
  "German dungeon porn",
  "Being on fire",
  "Using comedy as a coping mechanism",
  "Gandhi",
  "Your weird brother",
  "Birth control",
  "Nasty shit, like real sick stuff",
  "An erection that lasts longer than four hours",
  "A three-way with my wife and Shaquille O'Neal",
  "The past",
  "My genitals",
  "An endless stream of diarrhea",
  "Not reciprocating oral sex",
  "Flightless birds",
  "A good sniff",
  "50,000 volts straight to the nipples",
  "Da clubb",
  "Dead birds everywhere",
  "The arrival of the pizza",
  "Permanent Orgasm-Face Disorder",
  "The cool, refreshing taste of Pepsi®",
  "Irritable bowel syndrome",
  "Oprah",
  "Wondering if it's possible to get some of that salsa to go",
  "Bananas",
  "Me jubbly bubblies",
  "Switching to Geico®",
  "Peeing a little bit",
  "Wet dreams",
  "The Jews",
  "My cheating son-of-a-bitch husband",
  "Powerful thighs",
  "These hoes",
  "The only gay person in a hundred miles",
  "Having sex for the first time",
  "Donald J. Trump",
  "Kissing grandma on the forehead and turning off her life support",
  "A certain je ne sais quoi",
  "An AR-15 assault rifle",
  "My good bra",
  "Punching a congressman in the face",
  "Saying everything is okay when everything is clearly not okay",
  "Being rich",
  "Floating down the Hudson River with the other garbage",
  "Republicans",
  "Sniffing and kissing my feet",
  "A much younger woman",
  "Poverty",
  "Kamala Harris",
  "Committing suicide",
  "A loser like you",
  "A mistake",
  "Squirting",
  "Wizard music",
  "The Kool-Aid Man",
  "Explaining the difference between sex and gender",
  "Free samples",
  "Hurting those closest to me",
  "Feeding strawberries to my manslut",
  "The Three-Fifths Compromise",
  "Lactation",
  "Laughing over champagne flutes while the poor freeze to death outside",
  "Shutting up so I can watch the game",
  "Eating a hard boiled egg out of my husband's asshole",
  "Doing white people shit with a bunch of white people",
  "One titty hanging out",
  "Fucking all my dad's friends",
  "Drinking gasoline to see what it tastes like",
  "Inappropriate yodeling",
  "Ghosts",
  "50 mg of Zoloft daily",
  "Fucking my sister",
  "Braiding three penises into a Twizzler",
  "Vigorous jazz hands",
  "Getting fingered",
  "My Uber driver, Pavel",
  "GoGurt®",
  "Police brutality",
  "An abortion",
  "Preteens",
  "My fat daughter",
  "Clean drinking water",
  "Fading away into nothingness",
  "Darth Vader",
  "A sad handjob",
  "Exactly what you'd expect",
  "Critical race theory",
  "Adderall®",
  "Your mom",
  "Sideboob",
  "An octopus giving seven handjobs and smoking a cigarette",
  "My neck, my back, my pussy, and my crack",
  "J.D. Power and his associates",
  "Mouth herpes",
  "Sperm whales",
  "Women of color",
  "Men discussing their feelings in an emotionally healthy way",
  "Incest",
  "Pac-Man uncontrollably guzzling cum",
  "Casually suggesting a threesome",
  "Running out of semen",
  "God",
  "Backing over a kid with the Buick",
  "Pissing in my thirsty mouth",
  "Licking things to claim them as your own",
  "Jobs",
  "The placenta",
  "Lips that could suck the chrome off a doorknob",
  "The Bachelorette season finale",
  "Throwing grapes at a man until he loses touch with reality",
  "Establishing dominance",
  "Finger painting",
  "Old-people smell",
  "Getting crushed by a vending machine",
  "My inner demons",
  "A Super Soaker™ full of cat pee",
  "Aunt Jemima's® racist pancake sauce",
  "Cuddling",
  "However much weed $20 can buy",
  "Battlefield amputations",
  "Spaghetti? Again?",
  "Ronald Reagan",
  "A disappointing birthday party",
  "Nachos for the table",
  "Becoming a blueberry",
  "A tiny horse",
  "Crab",
  "Selling crack to children",
  "The Wendy's Spicy Chicken Sandwich",
  "Brown people",
  "Sexually active band geeks",
  "Pedophiles",
  "Yeast",
  "How bad my daughter fucked up her dance recital",
  "Rectangles",
  "Being fucking pathetic",
  "Poor people",
  "Only dating Asian women",
  "Putting children in cages",
  "Karen",
  "How amazing it is to be on mushrooms",
  "Judging everyone",
  "An all-white jury",
  "Getting married, having a few kids, buying some stuff, retiring to Florida, and dying",
  "Some god damn peace and quiet",
  "AIDS",
  "Pictures of boobs",
  "Strong female characters",
  "Getting decapitated by a helicopter",
  "Hospice care",
  "Getting really high",
  "The opioid epidemic",
  "Penis envy",
  "Gay conversion therapy",
  "Burgers and pussy",
  "Smelling of cum",
  "The KKK",
  "A pangender octopus who roams the cosmos in search of love",
  "Meth",
  "Cyanide",
  "Holding down a child and farting all over him",
  "A Bop It™",
  "A whole thing of butter",
  "Still being a virgin",
  "Solving problems with violence",
  "Getting cummed on",
  "Pixelated bukkake",
  "A lifetime of sadness",
  "A non-disclosure agreement",
  "Dick pics",
  "Racism",
  "Menstrual rage",
  "Sunshine and rainbows",
  "Joe Biden",
  "Three ounces of clean urine",
  "Doing drugs with my kids",
  "My gay best friend",
  "A gossamer stream of jizz that catches the light as it arcs through the morning air",
  "Executing a hostage every hour",
  "The rhythms of Africa",
  "Breaking out into song and dance",
  "Leprosy",
  "Gloryholes",
  "Nipple blades",
  "The heart of a child",
  "Puppies!",
  "Fellowship in Christ",
  "My wife having sex with your wife",
  "Waking up half-naked in a Denny's parking lot",
  "An older woman who knows her way around the penis",
  "Getting drugs off the street and into my body",
  "Daniel Radcliffe's delicious asshole",
  "Active listening",
  "Ethnic cleansing",
  "Itchy pussy",
  "Blowing my boyfriend so hard he shits",
  "A fuck-ton of almonds",
  "A cis man playing a trans woman",
  "Waiting till marriage",
  "NFTs",
  "Pretending to be a dentist",
  "The Devil himself",
  "Salvation",
  "Erectile dysfunction",
  "My collection of Japanese sex toys",
  "The Pope",
  "White people",
  "Tentacle porn",
  "My bright pink fuckhole",
  "How far I can get my own penis up my butt",
  "Having anuses for eyes",
  "Two Xanax and a bottle of wine",
  "My pet scorpion, Tina",
  "Danny DeVito",
  "The magic of live theatre",
  "Throwing a virgin into a volcano",
  "Accepting the way things are",
  "NBA superstar LeBron James",
  "Listening to her problems without trying to solve them",
  "Therapy",
  "Being fat and stupid",
  "Pooping back and forth. Forever",
  "Tearing that ass up like wrapping paper on Christmas morning",
  "More elephant cock than I bargained for",
  "A salty surprise",
  "The South",
  "The violation of our most basic human rights",
  "Saudi oil money",
  "Consensual sex",
  "Telling a shitty story that goes nowhere",
  "A good, strong gorilla",
  "Seeing my father cry",
  "Necrophilia",
  "Being a woman",
  "Getting into a pretty bad car accident",
  "Bill Nye the Science Guy",
  "Black people",
  "Prostate stimulation",
  "Lunchables™",
  "Bitches",
  "Some punk kid who stole my turkey sandwich",
  "Heartwarming orphans",
  "Spirit Airlines",
  "Bubble butt bottom boys",
  "Fiery poops",
  "Saying 'I love you'",
  "Inserting a Mason jar into my anus",
  "The true meaning of Christmas",
  "Whatever's in the fridge",
  "Owning and operating a Chili's franchise",
  "Estrogen",
  "Girls",
  "The Russians",
  "A bleached asshole",
  "Fucking the weatherman on live television",
  "PTSD",
  "Dark and mysterious forces beyond our control",
  "Smallpox blankets",
  "Masturbating",
  "Hobos",
  "Queefing",
  "My fuckslave, Reginald",
  "Cardi B",
  "Viagra®",
  "Soup that is too hot",
  "The ugliest boy in town",
  "Explaining how vaginas work",
  "Academy Award winner Meryl Streep",
  "Drinking alone",
  "Dick fingers",
  "Multiple stab wounds",
  "The death penalty",
  "A supportive touch on the lower back",
  "Anal beads",
  "Slaughtering innocent civilians",
  "Pulling out",
  "Being able to talk to elephants",
  "Horse meat",
  "A really cool hat",
  "Stalin",
  "A stray pube",
  "Worshipping that pussy",
  "Completely unwarranted confidence",
  "Doin' it in the butt",
  "A windmill full of corpses",
  "The whole enchilada",
  "Vladimir Putin",
  "The Patriarchy",
  "The glass ceiling",
  "Vomiting seafood and bleeding anally",
  "The American Dream",
  "Not wearing pants",
  "My balls on your face",
  "Pooping in a laptop and closing it",
  "Some bitch who loves pineapple",
  "Foreskin",
  "Getting crushed between Serena Williams' thighs",
  "Italians",
  "A fetus",
  "Firing a rifle into the air while balls deep in a squealing hog",
  "Natural gas",
  "Over 10,000 Guatemalan migrants",
  "Toxic masculinity",
  "My relationship status",
  "An unwanted pregnancy",
  "Marvel",
  "My boss",
  "Bees?",
  "Harry Potter erotica",
  "Giving birth to the Antichrist",
  "Three dicks at the same time",
  "Nazis",
  "8 oz. of Mexican black-tar heroin",
  "What that mouth do",
  "Dead parents",
  "Object permanence",
  "Opposable thumbs",
  "Racially-biased SAT questions",
  "The Great Depression",
  "Chainsaws for hands",
  "Nicolas Cage",
  "Like, whatever",
  "Explosions",
  "Not vaccinating my children because I am stupid",
  "Our dildo",
  "Huffing spray paint",
  "A man on the brink of orgasm",
  "Using a condom",
  "Invading Poland",
  "My vagina",
  "Assless chaps",
  "Murder",
  "Sipping kombucha like a smug piece of shit",
  "Her Majesty, Queen Elizabeth II",
  "Black Jesus",
  "Memes",
  "Sex with animals",
  "Being marginalized",
  "Hope",
  "Liberals",
  "A micropenis",
  "Committing treason",
  "A ball of earwax, semen, and toenail clippings",
  "A horde of Vikings",
  "Hot people",
  "Seething with quiet resentment",
  "An Oedipus complex",
  "Geese",
  "Extremely tight pants",
  "Fox News",
  "A little boy who won't shut the fuck up about dinosaurs",
  "Bryan Cranston, of all people",
  "Vehicular manslaughter",
  "Women's suffrage",
  "Some guy",
  "Judge Judy",
  "Climbing a telephone pole and becoming one with the T-Mobile network",
  "This month's mass shooting",
  "Barack Obama",
  "Illegal immigrants",
  "My horny, horny son",
  "The female orgasm",
  "Heteronormativity",
  "Crumbs all over the god damn carpet",
  "Corporate America",
  "The wifi password",
  "A time-traveling Chinese general from the Shang Dynasty",
  "A bird that shits human turds",
  "A mopey zoo lion",
  "Pro-life protesters",
  "Poor life choices",
  "My sex life",
  "Auschwitz",
  "Cocaine for lunch",
  "All the dudes I've fucked",
  "The clitoris",
  "The Big Bang",
  "Land mines",
  "The entire Mormon Tabernacle Choir",
  "A micropig wearing a tiny raincoat and booties",
  "Penis breath",
  "A gambling problem",
  "Man meat",
  "Me time",
  "The Underground Railroad",
  "Kayaking with my sluts",
  "Boppin' my flopper",
  "Lumberjack fantasies",
  "Goat",
  "Women in yogurt commercials",
  "Literally begging to die",
  "Being a motherfucking sorcerer",
  "My Black ass",
  "Genuine human connection",
  "Announcing that I am about to cum",
  "Grandma",
  "Friction",
  "Applying topical ointment to my grandfather's infected penis",
  "Being a dick to children",
  "One trillion dollars",
  "Drowning the kids in the bathtub",
  "Dying",
  "The gays",
  "The screams... the terrible screams",
  "Men",
  "The bombing of Nagasaki",
  "Fake tits",
  "The Amish",
  "Calling the cops on an innocent Black man",
  "My ugly face and bad personality",
  "A bitch slap",
  "A brain tumor",
  "Giggling like an anime girl",
  "Swamp ass",
  "The milkman",
  "Cards Against Humanity",

  // UK Edition exclusive white cards
  "An M. Night Shyamalan plot twist",
  "Fear itself",
  "The Daily Mail",
  "Morgan Freeman's voice",
  "James fucking Cordon",
  "The guys from Queer Eye",
  "A posh wank",
  "Catapults",
  "The Strictly Come Dancing final",
  "Flesh-eating bacteria",
  "Brutal austerity",
  "Elderly Japanese men",
  "Bogies",
  "Paedophiles",
  "Denying climate change",
  "Daniel Radcliffe's delicious arsehole",
  "Mad cow disease",
  "Flat out not giving a shit",
  "The prostate",
  "Fragile masculinity",
  "400 years of colonial atrocities",
  "Autocannibalism",
  "Oestrogen",
  "Blowing up Parliament",
  "Slapping your knees to signal your imminent departure",
  "Shiny objects",
  "Ecstasy",
  "The homosexual agenda",
  "Cheeky bum sex",
  "The inevitable heat death of the universe",
  "Used knickers",
  "A sea of troubles",
  "A bit of slap and tickle",
  "Waking up in Idris Elba's arms",
  "Faffing about",
  "Your mum",
  "Muhammad (Peace Be Upon Him)",
  "A middle-aged man on roller skates",
  "Licking the Queen",
  "The violation of our most basic human rights",
  "Oompa-Loompas",
  "A bag of magic beans",
  "Chunks of dead hitchhiker",
  "A time travel paradox",
  "Giving 110%",
  "Extremely tight trousers",
  "Comprehensive understanding of the Irish backstop",
  "Danny Dyer",
  "Martin Lewis, Money Saving Expert",
  "A saxophone solo",
  "A fanny fart",
  "German Chancellor Angela Merkel",
  "A snapping turtle biting the tip of your penis",
  "A pyramid of severed heads",
  "Forced sterilisation",
  "Little boy penises",
  "Madeleine McCann",
  "Justin Bieber",
  "Slapping Nigel Farage over and over",
  "The bastard seagull who stole my chips",
  "Famine",
  "7 dead and 3 in critical condition",
  "My Uber driver, Ajay",
  "Spectacular abs",
  "Sweet, sweet vengeance",
  "Kissing nan on the forehead and turning off her life support",
  "Tap dancing like there's no tomorrow",
  "Blowing my boyfriend so hard he shits",
  "A Ginsters pasty and three cans of Monster Energy",
  "A balanced breakfast",
  "RoboCop",
  "The end of days",
  "A deep-rooted fear of the working class",
  "A salad for men that's made of metal",
  "Sexual tension",
  "Not giving a shit about the Third World",
  "The petty troubles of the aristocracy",
  "A meat raffle!",
  "World peace",
  "Lads",
  "A white van man",
  "Wanking into a pool of children's tears",
  "My soul",
  "Queuing",
  "Seeing my father cry",
  "My cheating prick of a husband",
  "Doing the right thing",
  "Unfathomable stupidity",
  "An oversized lollipop",
  "Trench foot",
  "A nice cup of tea",
  "Being a witch",
  "A Fleshlight®",
  "10,000 Syrian refugees",
  "Blood, sweat, and tears",
  "Some foundation, mascara, and a touch of blush",
  "A slightly salty toad in the hole",
  "Teaching a robot to love",
  "Looking in the mirror, applying lipstick, and whispering 'tonight, you will have sex with Tom Cruise'",
  "All my gentleman suitors",
  "Queen Elizabeth's immaculate anus",
  "The smell of a Primark",
  "Some bloody peace and quiet",
  "Seppuku",
  "A sober Irishman who doesn't care for potatoes",
  "Discovering he's a Tory",
  "Egging an MP",
  "The Black Death",
  "Daddies® Brown Sauce",
  "Kamikaze pilots",
  "Huge biceps",
  "Spontaneous human combustion",
  "Giving birth to the Antichrist",
  "A fanny fart",
  "Peeing a little bit",
  "Dry heaving",
  "Jimmy Savile",
  "Getting married, having a few kids, retiring to the south of France, and dying",
  "Scottish independence",
  "Making a pouty face",
  "Ainsley Harriott",
  "Diversity",
  "Sitting in a jar of vinegar all night because I am gherkin",
  "The penny whistle solo from 'My Heart Will Go On'",
  "Ryanair",
  "The Force",
  "Cottaging",
  "Flying sex snakes",
  "Raptor attacks",
  "Spaniards",
  "The French",
  "Teenage pregnancy",
  "Being fucking stupid",
  "Dogging",
  "Serfdom",
  "Passive-aggressive Post-it notes",
  "Tories",
  "Scousers",
  "Arnold Schwarzenegger",
  "72 virgins",
  "Somali pirates",
  "David Bowie flying in on a tiger made of lightning",
  "Grabbing my man by his love handles and fucking his big arse",
  "The way James Bond treats women",
  "Polish people",
  "A falcon with a cap on its head",
  "My mate Dave",
  "The North",
  "Chemical weapons",
  "Me time",
  "Dead babies",
  "Kourtney, Kim, Khloe, Kendall, and Kylie",
  "A vindaloo poo",
  "Sex with Patrick Stewart",
  "Mutually-assured destruction",
  "Radical Islamic terrorism",
  "Child beauty pageants",
  "However much weed £20 can buy",
  "Nicki Minaj",
  "Filling my briefcase with business stuff",
  "My little boner",
  "LYNX® Body Spray",
  "A general lack of purpose",
  "The unstoppable tide of Islam",
  "Shitting out a perfect Cumberland sausage",
  "Boris Johnson",
  "Brexit",
  "A hen night in Slough",
  "The Welsh",
  "Getting the same Boots Meal Deal every day for six years",
  "Crumbs all over the bloody carpet",
  "Knife crime",
  "A mopey zoo lion",
  "Women in yoghurt adverts",
];
